feat(portal): create initial portal database schemas
cuhacking/2025 pull request #134
Opened 2024-10-06 03:49 UTC by JeremyFriesenGitHub

## 🚩 Linked issue

[Here is the linked issue](https://github.com/cuhacking/2025/issues/133).

## 🛠 How does this PR address the issue(s)? How does it solve the problem?

This PR implements a Drizzle PSQL DB for the Portal User Profile creation. For now, this is a temporary, rough-draft, tentative schema, that can be changed at any time. 

## 🧠 Describe any alternatives you've considered

Drizzle is type safe, we can get direct access to attributes, we can make queries easily and we are able to migrate easily and efficiently towards other databases or make/incorporate changes easily into the db if needed. This is why setting up an ORM is extremely critical for our backend infrastructure and will save a lot of time. 

## ✨ Dependency Changes (if applicable)

N/A

## 📸 Before and After Screenshots (if applicable)

|        Before         |        After         |
| :-------------------: | :------------------: |
|  ![cuHacking Database Design-2024-09-28-192630](https://github.com/user-attachments/assets/6ff579b0-1e8a-4fa6-bd43-158ec003b741)| ![cuHacking Database Design-2024-10-06-034159](https://github.com/user-attachments/assets/8a0f2d47-6b32-4d15-8580-6100f0017720)|

## ✍️ Additional comments (if applicable)

We updated a bit of the database design. There are more changes to come for that design (for instance, UserPreferances table should be merged with the User table). But for now, we are going to set everything up and we will be able to run migrations later thanks to DrizzleORM.

2024-10-11 11:07 UTC, MFarabi619 commented
@JeremyFriesenGitHub Is it possible to link a publicly visible live link to the actual mermaid code?

2024-10-12 16:18 UTC, JeremyFriesenGitHub commented
> @JeremyFriesenGitHub Is it possible to link a publicly visible live link to the actual mermaid code?

i have no idea atp, im not sure.

2024-10-13 01:54 UTC, JeremyFriesenGitHub commented
> @JeremyFriesenGitHub Is it possible to link a publicly visible live link to the actual mermaid code?

After looking at this for a while, I have no idea what u mean by this. Could you clarify @MFarabi619

2024-10-13 04:38 UTC, MFarabi619 commented
@HasithDeAlwis

2024-10-15 08:54 UTC, MFarabi619 commented
chore: elaborate on behaviour for fix commits

I know it's strange that I nitpick on commit messages, it's because I review code very differently from most others.

When I review code, I go by scanning commit history.
- Provides me with more context
- Allows me to understand the contributor's thought process better because I go through it linearly/chronologically

![image](https://github.com/user-attachments/assets/31d1bd31-4f36-43e9-9442-18642ccbaef4)

For `fix` commits, it's implied that it was a bug by the type, and the behaviour wasn't intended. You want to avoid mentioning the types and scopes in the body of the message.

When you're scanning the commit history, which one is more helpful?

 > fix(docs): bug fix for tools-overview page 
 > fix(wiki): bug fix for next button for wiki home page

Or

 > fix(docs/tools-overview): page displaying 404 error due to missing image loader in nextjs config
 > fix(docs/wiki): clicking next button goes to _____ instead of _____

The tools-overview page was completely crashed and non functional for a bit due to the missing image loader, where was the breaking change introduced and how'd that make it past tests? :/

Avoid making bugfixes from unmerged features on the PR unless in dire emergencies that require velocity. Just squash/amend those fixes to your feature. A `fix` implies that this bug already existed on main. A high volume of fixes is a strong sign for us to improve testing and/or review processes.

If the commit message is redundant/misleading, that makes it very difficult to review code.
- My personal preference it to have longer commit message bodies
- I try to use the type and scopes to indicate location

Essentially answering who, what, where, when, why as much as possible. The commit message metadata already has the who, and when. With your commit message you want to answer the what, where, and why.

 > fix(libraries/db): bug fix for links on db page
 - What link was it?
 - What was not working as intended?
 - If this was a content change, it can be `docs(libraries/db): fix broken link..`, if this was a framework/layout level change then it should be `fix(docs)...`
 
 > feat(libs/db): initialize database schemas
 - Why is this scope `libs` and the previous one `libraries`?
 - Are we not using the `api` scope to signify back-end changes as mentioned in the [contribution guidelines](https://docs.cuhacking.ca/contribution-guidelines/conventional-commits#examples)?
 
 > docs(libraries/db): add mermaid erd diagram to docs
 - The type already indicates that it's the docs project, you don't need to mention it again in the body
 
Codeowners are expected to look after the conventions of their respective areas as well. Haven't completed my review, will do another pass later.

2024-10-16 16:25 UTC, HasithDeAlwis requested changes
Can we add TODO comments to add `checks`. Read more [here](https://orm.drizzle.team/docs/indexes-constraints#check). 
I think all URLs need this. 

Other than that good work on this, let's clean up a tiny bit of things then get this merged in.

2024-10-16 16:25 UTC, HasithDeAlwis commented on apps/docs/next.config.mjs
> +  images: {
might be worth adding a comment here explaining why we need this!

2024-10-16 16:25 UTC, HasithDeAlwis commented on libs/db/src/schema/user.ts
> +export const genderEnum = pgEnum('gender', ['male', 'female', 'other'])
Might as well do this now, agree with this 👍

2024-10-16 16:25 UTC, HasithDeAlwis commented on libs/db/src/schema/session.ts
>  export const session = pgTable('session', {
are we good to make this table before finalizing the auth provider?

2024-10-16 16:25 UTC, HasithDeAlwis commented on libs/db/src/schema/school.ts
> +export const levelOfStudyEnum = pgEnum('levelOfStudy', ['graduateSchool', 'highSchool'])
no need for highschool right now, should be added on later imo

2024-10-16 16:25 UTC, HasithDeAlwis commented on libs/db/src/schema/school.ts
> +export const school = pgTable('school', {
Good idea to add a location to this as well

2024-10-16 16:25 UTC, HasithDeAlwis commented on libs/db/src/schema/socialMedia.ts
> +  platformName: varchar('platformName', { length: 16 }),
this should reference another `Platform` table so that we can regulate the social medias that we accept

2024-10-16 16:25 UTC, HasithDeAlwis commented on libs/db/src/schema/resume.ts
> +  hasPrivacyToggle: boolean('hasPrivacyToggle').default(false),
good touch 👍

2024-10-18 15:14 UTC, MFarabi619 commented
Closing as stale

2025-02-23 08:57 UTC, closed without merging